In [1]:
import requests
from bs4 import BeautifulSoup,SoupStrainer
import pandas as pd
from IPython.display import Markdown, display,HTML,Image
from selenium import webdriver
import time
from pandas.plotting import table 
import matplotlib.pyplot as plt
import string

import warnings
warnings.filterwarnings("ignore")

# Borrowed the offset idea from this (much more professionally done) tableau page
# https://public.tableau.com/app/profile/heidi.stockton/viz/PuzzlesofJaneStreet/JaneStreet
# No adjustments for similar names etc (apologies)

In [2]:
# get the solution links
pages = ['https://www.janestreet.com/puzzles/archive/index.html']+['https://www.janestreet.com/puzzles/archive/page'+str(i)+'/index.html' for i in range(2,13)]
links =  ['https://www.janestreet.com/puzzles/current-puzzle/']
for url in pages:
    res = requests.get(url,verify=False)
    soup = BeautifulSoup(res.content, 'html.parser')
    links += ['https://www.janestreet.com/'+i['href'] for i in soup.find_all('a', {'class' :'solution-link'})]

In [3]:
# scrape the names of solvers
participants = []
order = 1
driver = webdriver.Firefox()
for url in links:
    driver.get(url)
    time.sleep(10)
    htmlSource = driver.page_source
    soup = BeautifulSoup(htmlSource, 'html.parser')
    participants += [[str(url).split("/")[-1],i.split(" (")[0],order] for i in soup.find_all('p', {'class' :'correct-submissions'})[0].stripped_strings]
    order +=1

In [4]:
outputs = []
for newcomer_offset in [10]:
    df = pd.DataFrame(participants,columns = ['puzzle','Name','Order'])
    df['Name']=df['Name'].str.lstrip("1234567890. ")
    df['Name'] = df['Name'].str.title()
    df2 = df[['Name','Order']].groupby('Name').agg({'Name':['count'],'Order': ['max']})
    df2.columns = [' '.join(col).strip() for col in df2.columns.values]
    df2.columns = ['Solved','Attempts']
    df2['Score']=df2['Solved']/(df2['Attempts']+ newcomer_offset)
   
df2.sort_values(['Score','Solved'],ascending=False)[:15]

                            Solved  Attempts     Score
Name
Evan Semet                      49        50  0.816667
Senthil Rajasekaran             74        85  0.778947
Karl Mahlburg                   64        74  0.761905
Gareth Owen                     56        65  0.746667
Aaditya Raghavan                58        68  0.743590
Danica Xiong                    31        32  0.738095
Lazar Ilic                      53        62  0.736111
Calvin Pozderac                 76        98  0.703704
Miguel Barbosa Pereira          37        45  0.672727
Josh Richman                    30        37  0.638298
Blaine Hill                     25        30  0.625000
Moritz Kunze & Hai-Yen Van      25        30  0.625000
Anton 3 Terekhov                28        36  0.608696
Brandon Cage                    23        28  0.605263
David Korff                     15        15  0.600000

In [5]:
df2.sort_values('Solved',ascending=False)[:15]

                        Solved  Attempts     Score
Name
Calvin Pozderac             76        98  0.703704
Senthil Rajasekaran         74        85  0.778947
Karl Mahlburg               64        74  0.761905
Aaditya Raghavan            58        68  0.743590
Sean Egan                   58        92  0.568627
Gareth Owen                 56        65  0.746667
Lazar Ilic                  53        62  0.736111
Keith Schneider             52        89  0.525253
Evan Semet                  49        50  0.816667
Sanandan Swaminathan        40        61  0.563380
Heidi Stockton              40       111  0.330579
Sébastien Geeraert          38        83  0.408602
Miguel Barbosa Pereira      37        45  0.672727
Danica Xiong                31        32  0.738095
Cubist                      31        67  0.402597

In [6]:
import xlwings as xw
sht = xw.Book().sheets[0]
sht.range('a1').options(index=False).value =  df

In [7]:
df[df['Name']=='Gareth Owen']

                                       puzzle         Name  Order
462                                            Gareth Owen      1
713                     shut-the-box-solution  Gareth Owen      2
1605                  robot-baseball-solution  Gareth Owen      3
1943                        hooks-11-solution  Gareth Owen      4
2345              dogs-playing-poker-solution  Gareth Owen      5
2640                 robot-road-trip-solution  Gareth Owen      6
2823             some-ones-somewhere-solution  Gareth Owen      7
3137                  number-cross-5-solution  Gareth Owen      8
3797               sum-one-somewhere-solution  Gareth Owen      9
4688               hall-of-mirrors-3-solution  Gareth Owen     10
5930          top-score-give-or-take-solution  Gareth Owen     11
6405          somewhat-square-sudoku-solution  Gareth Owen     12
6877                     games-night-solution  Gareth Owen     13
8166                beside-the-point-solution  Gareth Owen     14
8466                  knight-moves-6-solution  Gareth Owen     15
9571                        fences-2-solution  Gareth Owen     16
10232               tree-edge-triage-solution  Gareth Owen     17
10294             many-happy-returns-solution  Gareth Owen     18
10407               altered-states-2-solution  Gareth Owen     19
11085                 number-cross-4-solution  Gareth Owen     20
11456         robot-capture-the-flag-solution  Gareth Owen     21
11759                       hooks-10-solution  Gareth Owen     22
12054                some-off-square-solution  Gareth Owen     23
12371                 some-f-squares-solution  Gareth Owen     24
12703              hall-of-mirrors-2-solution  Gareth Owen     25
12768                 knight-moves-5-solution  Gareth Owen     26
12818                   a-weird-tour-solution  Gareth Owen     27
12957            getting-from-a-to-b-solution  Gareth Owen     28
13082                 single-cross-2-solution  Gareth Owen     29
13288                   choco-banana-solution  Gareth Owen     30
13669                        hooks-9-solution  Gareth Owen     31
13915                     game-night-solution  Gareth Owen     32
14096               arc-edge-acreage-solution  Gareth Owen     33
14245                robot-long-jump-solution  Gareth Owen     34
14359  twenty-four-seven-four-in-one-solution  Gareth Owen     35
14925                    lesses-more-solution  Gareth Owen     36
15275                      die-agony-solution  Gareth Owen     37
16151                the-marshy-mess-solution  Gareth Owen     39
16275                new-york-minute-solution  Gareth Owen     41
16482           andys-morning-stroll-solution  Gareth Owen     42
16706                  block-party-4-solution  Gareth Owen     43
17084                   almost-magic-solution  Gareth Owen     45
17258                         eldrow-solution  Gareth Owen     47
17348                        hooks-8-solution  Gareth Owen     48
17732               split-division-2-solution  Gareth Owen     50
17962          robot-swimming-trials-solution  Gareth Owen     51
18193                 knight-moves-4-solution  Gareth Owen     52
18428               robot-tug-of-war-solution  Gareth Owen     53
18505               it-s-symmetric-2-solution  Gareth Owen     54
18735               bracketology-101-solution  Gareth Owen     57
18927                        hooks-7-solution  Gareth Owen     59
19125              figurine-figuring-solution  Gareth Owen     60
19240     twenty-four-seven-2-by-2-2-solution  Gareth Owen     61
19365                        tangled-solution  Gareth Owen     63
19421               study-and-ponder-solution  Gareth Owen     64
19738                    what-a-trit-solution  Gareth Owen     65